name: election
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - numpy
  - pandas
  - pandera
  - pip
  - plotly
  - setuptools
  - pytorch=1.6.0
  - torchvision=0.7.0
  - pip:
    - sentence-transformers==0.3.5
    - sklearn
    - transformers==3.0.2